name: Build KidsOS image

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build custom image
        uses: blue-build/github-action@v1
        with:
          recipe: recipes/recipe.yml
          push: true
          registry_username: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          maximize_build_space: true
          cli_args: "--no-sign"